# Generated by Django 3.1.4 on 2020-12-17 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de39b87d-5df3-48e7-ba40-42e8a7f53eb7'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
