# Generated by Django 3.1.4 on 2020-12-17 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201217_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('171d563f-7566-4930-ae57-383b8ca5a144'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
