# Generated by Django 3.1.4 on 2020-12-20 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201217_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22bfadbf-6f0a-42dc-913b-5de67fe4589a'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
