# Generated by Django 3.1.4 on 2020-12-21 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201221_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9f0ed7a-eac1-4836-a6b1-58b560e1ff48'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
