# Generated by Django 3.1.4 on 2020-12-21 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201221_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e5c51e1c-69f9-4269-8e78-6e7a1b5554a7'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
