# Generated by Django 3.1.4 on 2020-12-21 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201221_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b3bd31d-e9a7-48d5-bb5a-b1cd05f89c17'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
