# Generated by Django 3.1.4 on 2020-12-21 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201221_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('783ceae1-399b-4a3e-aa69-49063ace777a'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
