# Generated by Django 3.1.4 on 2020-12-21 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201221_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27001359-fd30-4102-8c89-5676356ad4b8'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
