# Generated by Django 3.1.4 on 2020-12-21 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20201221_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f11cecd-f76b-4741-bb13-5f1c1375a278'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
