# Generated by Django 3.1.4 on 2021-01-05 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20201221_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ecd0b7d-92ed-4b9c-8583-bb039c7f20d1'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
