# Generated by Django 3.1.4 on 2021-01-05 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210105_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('136b3438-82d0-4f78-a321-a61c0fc7e835'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
