# Generated by Django 3.1.4 on 2021-01-09 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210108_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb558399-1ffb-4bc5-9ff9-e58afdf9aad6'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
