# Generated by Django 3.1.4 on 2021-01-13 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210112_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e77c7bfc-51b0-4728-85d2-fc23bc217a32'), help_text='Unique ID of this book', primary_key=True, serialize=False),
        ),
    ]
